### ISSUE TITLE
OBS 31.0.0

### ISSUE THREAD

**Issue by Tomcatt** [fzwoch/obs-teleport#109]
Hello,

I wasn't able to get OBS-Teleport to work under windows 11 w/ OBS 31.0.0.  v30.2.3 worked.  Under Linux (receiving computer) it just got compiled to the latest version of OBS and Teleport works over there.  Maybe I'm missing something.

Thanks.

**Comment by fzwoch** [comment]
Does it not load at all? Is there something in the log?

Perhaps it needs a recompile with more recent headers..

**Comment by fzwoch** [comment]
I just tried 0.7.3 on v31 in my Windows 10 VM - that seemed to work fine. Perhaps the OBS update somehow reset the network access permission on your end?

**Comment by etrusci-org** [comment]
Hi there

Windows: 11
OBS: 31.0.0

OBS 31.0 crashed on startup after I updated Teleport to 0.7.3.

I removed all Teleport files from the OBS directories and re-run Teleport 0.7.3.exe to install it again.

Then OBS started again and Teleport is loaded. Didn't test functionality yet because other PC still needs to be updated, but if it loads it should also work i guess :)

**Comment by fzwoch** [comment]
0.7.2 started to place itself in another location (OBS recommended one, outside of the OBS directory). If you had the old one around I guess it could have caused some trouble. Upgrading from 0.7.2 to 0.7.3 should not be affected, so I guess you updated from on older version?

**Comment by fzwoch** [comment]
Thanks for checking. I have added the note to the current release as well.

Closing this in the hope this was @Tomcatt 's issue as well. If not, please re-open.

**Comment by Tomcatt** [comment]
Thank you.  Windows is good.  I need to start one for Linux.
