### ISSUE TITLE
[Feature Request] Add an option for max latency (for consistency on delay)

### ISSUE THREAD

**Issue by Lohkdesgds** [fzwoch/obs-teleport#31]
I've got a bad router. It sometimes run low latency, sometimes it feels like 2+ seconds. It could have an option to just say "lock at 5 seconds" so it buffers up to that and keeps latency perfectly sync. Of course it should drop frames/packets if things just fail (so it wouldn't desync), but like a stream on Twitch or YouTube, this buffer keeps things going perfectly at a cost of some seconds.

Btw THANK YOU A LOT for this plugin, it is AWESOME! ;P

**Comment by fzwoch** [comment]
The plugin allows a buffer of 20 frames (currently). Not more. If that is exceeded data gets skipped. There is no latency logic in this plugin. So if there are additional latency effects it is probably due to internals in OBS.

Maybe you can realize this 5 second buffer by adding a video delay filter to the teleport source. But it is up again on OBS side how this is implemented. This plugin just handles data to OBS. It should be OBS job to decide when and how to render it the best possible way.

**Comment by Lohkdesgds** [comment]
Interesting, thank you.
