### ISSUE TITLE
Performance issue.

### ISSUE THREAD

**Issue by ItsVinnyX** [fzwoch/obs-teleport#36]
So I used NDI before but unfortunately, the Screen Capture module footage was lagging/choppy for me, the audio was fine though. I tried with Screen Capture HX and the gameplay was smooth but I ran into the issue with the audio being delayed. 

I learned about Teleport and was hopeful. I set it up on both machines and the audio was surprisingly on point with practically zero notice in delay. However, I noticed a sudden delay in gameplay footage between swapping from different IP selections within the menu. One was noticeably better than the other. Well, I found the correct one without delay, but the moment I hopped into a game, I had terrible FPS... I mean it was from 100+ to about 30 FPS. I did some investigation and the moment I disabled "Teleport" on the gaming rig "The Sender" my frames shot right up.

Any clue on what could be causing this? Literally worked perfectly for my needs but that is the setback.

**Gaming Rig Specifications:**
i9-10850k
RTX 3090
32 GB DDR4 RAM

**Streaming Rig Specifications:**
Ryzen 5 3600
RTX 3060Ti
16 GB DDR4 RAM

_**Both operating on Windows 11 Pro.**_

**Comment by fzwoch** [comment]
If you feel you can reproduce something that gives abnormal performance figures, feel free to reopen. I feel like current performance bottlenecks are simply bottlenecks. If the fps/resolution is too much for the target/destination machines it will will just fail. That is technical limitation, rather than a bug (unless you find some really odd behaviour).

**Comment by YorVeX** [comment]
Maybe it's still worth investigating what exactly is bottlenecking, it would help with optimizing the systems for Teleport.

In my test setup I send a preview of the final mixed stream out to a laptop with only a quality setting of 40 because it's shown there in a rather small window anyway and it's sufficient for the preview. In this setup the whole system has a CPU load of around 35%. But just for testing I cranked up the quality of this to 100 and surely I will get encoding lag from hell, something like 2 FPS on the receiver but the CPU load only went up to 38% on the sender system.

This is on a Ryzen Threadripper 1950X, so its strength is in it having 16 physical (32 logical) cores. Maybe Teleport only uses one CPU core for encoding? Or at least not all of them?

**Comment by fzwoch** [comment]
Make sure the network is not the bottleneck at 100%. Images should be encoded/decoded in parallel always. So it should spread across all cores.

**Comment by YorVeX** [comment]
Good point, will test again later.

**Comment by YorVeX** [comment]
OK, this is interesting. Sending a 900p stream with quality 100 to only a PC (2.5 GBit/s interface) doesn't lag, task manager says 430 MBit/s. Sending the same stream to a laptop (1 GBit/s interface) is lagging and also showing lots of encoding lag on the sender side. Task manager says 430 MBit/s most of the time but sometimes with dips down to 370 MBit/s.

I wonder why a receiver that doesn't perform well lags the sender. Is it because the sender waits for confirmations for each packet/frame/chunk/whatever unit from the receiver?

As a result of this behavior if the stream is sent to both the laptop and the PC also the stream on the PC lags. That means one "bad" receiver can also make other receivers lag that on their own would perform well.
Interestingly even though the sender shows dropped frames due to encoding lag when I record the session the lags aren't in the recording, everything looks good there.

Using Teleport in a bit bigger setups is really not trivial with all those rather counter-intuitive pitfalls 😛 

While I have once more learned something new through this test I still don't know what the actual bottleneck is, the laptop is at 44% CPU and as I said has a 1 GBit/s interface when only 430 MBit/s are needed, also a speed test on the laptop shows that it reaches at least 950 MBit/s.

**Comment by fzwoch** [comment]
If you have 430mbps on one client but have two connected, you will end up with 860mbps on the sender. With some overhead and maybe not perfect implementation that gets close to max. And yes, one receiver can slow down the other if its not fast enough consuming.

**Comment by YorVeX** [comment]
Nah, the sender has a 10 GBit/s connection, the PC receiver 2.5 GBit/s and the laptop a 1 GBit/s connection so doubling for the sender shouldn't bottleneck at all (also with a measurement tool I can see that between sender and receiver PC the net speed it reaches is actually 2.37 GBit/s).
